# Generated by Django 3.2.4 on 2021-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='rollnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='year',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(default='', max_length=16),
        ),
    ]
