# Generated by Django 3.2.4 on 2021-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_questionanswers_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswers',
            name='id',
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='qid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
