# Generated by Django 3.2.4 on 2021-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20210621_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswers',
            name='qid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
