# Generated by Django 3.2.4 on 2021-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_userid', models.CharField(max_length=20)),
                ('Teacher_password', models.CharField(max_length=20)),
            ],
        ),
    ]
